config/routes.rb
Rails.application.routes.draw do
  root to: 'sales#index'  # Isso define a página inicial como a action 'index' no controlador Sales
  
  resources :sales do
    collection do
      delete :destroy_all
      get :export, to: 'sales#export'
    end
  end
  
  # Outras rotas podem ir aqui
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/sale.rb
class Sale < ApplicationRecord
  validates :purchaser_name, presence: true
  validates :item_description, presence: true
  validates :item_price, presence: true
  validates :purchase_count, presence: true
  validates :merchant_address, presence: true
  validates :merchant_name, presence: true
end

app/models/upload_history.rb
class UploadHistory < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/sales_controller.rb
require 'csv'
require 'axlsx'
require 'stringio'

class SalesController < ApplicationController
  def new
    @sale = Sale.new
  end

  def create
    file = params[:file]

    if file.present?
      data = File.read(file.tempfile).split("\n").map { |line| line.split("\t") }

      total_income = 0
      data[1..-1].each do |row| # Ignora a linha de cabeçalho
        purchaser_name, item_description, item_price, purchase_count, merchant_address, merchant_name = row

        # Remover R$ da descrição e converter para float
        item_description.gsub!(/R\$?\s*/, '')

        # Extrair o valor numérico da descrição, se houver
        extracted_price = item_description.scan(/[\d,]+/).first
        extracted_price = extracted_price.tr(',', '.').to_f if extracted_price # Converte para float e substitui vírgula por ponto

        # Converte item_price para float e verifica se já foi fornecido
        item_price = item_price.to_f

        # Se a descrição contém um preço e o preço não foi fornecido, usar o preço extraído
        item_price = extracted_price if extracted_price && item_price.zero?

        # Se a descrição contém um preço, remova-o da descrição
        item_description.gsub!(/[\d,]+/, '')

        # Debug: Imprimir os dados que estão sendo enviados
        puts "Creating Sale: #{purchaser_name}, #{item_description}, #{item_price}, #{purchase_count}, #{merchant_address}, #{merchant_name}"

        # Use create! para verificar se há erros
        begin
          Sale.create!(
            purchaser_name: purchaser_name.strip, # Remove espaços em branco
            item_description: item_description.strip, # Remove espaços em branco
            item_price: item_price,
            purchase_count: purchase_count.to_i,
            merchant_address: merchant_address.strip, # Remove espaços em branco
            merchant_name: merchant_name.strip # Remove espaços em branco
          )

          total_income += item_price * purchase_count.to_i
        rescue ActiveRecord::RecordInvalid => e
          puts "Erro ao criar venda: #{e.message}"
          flash[:alert] = "Erro ao processar a linha: #{row.inspect}. #{e.message}"
        end
      end

      flash[:notice] = "Upload feito com sucesso!"
      redirect_to sales_path
    else
      redirect_to new_sale_path, alert: "Por favor, envie um arquivo."
    end
  end

  def index
    @sales = Sale.all
    @total_income = @sales.sum("item_price * purchase_count")
  end

  def edit
    @sale = Sale.find(params[:id])
  end

  def update
    @sale = Sale.find(params[:id])
    if @sale.update(sale_params)
      redirect_to sales_path, notice: 'Venda atualizada com sucesso.'
    else
      render :edit
    end
  end

  def destroy
    @sale = Sale.find(params[:id])
    @sale.destroy
    redirect_to sales_path, notice: 'Venda excluída com sucesso.'
  end

  def destroy_all
    Sale.delete_all
    redirect_to sales_path, notice: 'Todas as vendas foram excluídas com sucesso.'
  end

  def export
    @sales = Sale.all
    respond_to do |format|
      format.csv { send_data to_csv(@sales), filename: "vendas-#{Date.today}.csv" }
      format.xlsx do
        io = StringIO.new
        to_xlsx(@sales, io)
        io.rewind
        send_data io.string, filename: "vendas-#{Date.today}.xlsx", type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
      end
    end
  end

  private

  def sale_params
    params.require(:sale).permit(:purchaser_name, :item_description, :item_price, :purchase_count, :merchant_address, :merchant_name)
  end

  def to_csv(sales)
    CSV.generate(col_sep: ";", headers: true) do |csv|
      csv << ["Nome do Comprador", "Descrição do Item", "Preço do Item", "Quantidade Comprada", "Endereço do Comerciante", "Nome do Comerciante"]
      
      sales.each do |sale|
        csv << [sale.purchaser_name, sale.item_description, sale.item_price, sale.purchase_count, sale.merchant_address, sale.merchant_name]
      end
    end
  end

  def to_xlsx(sales, io)
    package = Axlsx::Package.new
    package.workbook.add_worksheet(name: "Vendas") do |sheet|
      sheet.add_row ["Nome do Comprador", "Descrição do Item", "Preço do Item", "Quantidade Comprada", "Endereço do Comerciante", "Nome do Comerciante"]
      
      sales.each do |sale|
        sheet.add_row [sale.purchaser_name, sale.item_description, sale.item_price, sale.purchase_count, sale.merchant_address, sale.merchant_name]
      end
    end

    io.write package.to_stream.read
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ImportMaster</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  
  <!-- Importmap para gerenciar scripts -->
  <%= javascript_importmap_tags %>
</head>

<body class="bg-light">
  <header class="bg-primary text-white p-4 mb-4 sticky-top">
    <div class="container">
      <h1 class="display-4">ImportMaster</h1>
      <nav>
        <%= link_to 'Novo Upload', new_sale_path, class: 'btn btn-light me-2' %>
        <%= link_to 'Ver Vendas', sales_path, class: 'btn btn-outline-light' %>
      </nav>
    </div>
  </header>

  <div class="container">
    <main>
      <%= yield %>
    </main>

    <footer class="mt-4 text-center">
      <p>&copy; <%= Time.now.year %> ImportMaster - Jeferson B.</p>
    </footer>
  </div>

  <% flash.each do |key, message| %>
    <div class="alert alert-<%= key == 'notice' ? 'success' : 'danger' %> position-fixed bottom-0 end-0 m-3 fade" style="z-index: 1050;">
      <%= message %>
    </div>
  <% end %>

  <script>
    document.addEventListener('DOMContentLoaded', function () {
      const alerts = document.querySelectorAll('.alert');
      alerts.forEach(alert => {
        // Adiciona a classe 'show' para a animação de entrada
        alert.classList.add('show');
        
        // Tempo que o alerta fica visível
        const displayTime = 5000; // 5 segundos
        const fadeOutTime = 500; // 0.5 segundos para a animação de saída
        
        setTimeout(() => {
          alert.classList.remove('show'); // Remove a classe para iniciar a animação de saída
          setTimeout(() => {
            alert.style.display = 'none'; // Remove o alerta após a animação de saída
          }, fadeOutTime); // Tempo da animação de saída
        }, displayTime); // Tempo que o alerta fica visível
      });
    });
  </script>

  <!-- jQuery e Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

app/views/sales/edit.html.erb
<h1 class="text-center mb-4">Editar Venda</h1>

<%= form_with(model: @sale, local: true, html: { class: "form" }) do |form| %>
  <% if @sale.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <h2><%= pluralize(@sale.errors.count, "erro") %> proibiu esta venda de ser salva:</h2>
      <ul>
        <% @sale.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="scrollable mb-3" style="max-height: 400px; overflow-y: auto;">
    <div class="form-group mb-3">
      <%= form.label :purchaser_name, class: "form-label" %>
      <%= form.text_field :purchaser_name, class: "form-control" %>
    </div>

    <div class="form-group mb-3">
      <%= form.label :item_description, class: "form-label" %>
      <%= form.text_field :item_description, class: "form-control" %>
    </div>

    <div class="form-group mb-3">
      <%= form.label :item_price, class: "form-label" %>
      <%= form.number_field :item_price, class: "form-control" %>
    </div>

    <div class="form-group mb-3">
      <%= form.label :purchase_count, class: "form-label" %>
      <%= form.number_field :purchase_count, class: "form-control" %>
    </div>

    <div class="form-group mb-3">
      <%= form.label :merchant_address, class: "form-label" %>
      <%= form.text_field :merchant_address, class: "form-control" %>
    </div>

    <div class="form-group mb-3">
      <%= form.label :merchant_name, class: "form-label" %>
      <%= form.text_field :merchant_name, class: "form-control" %>
    </div>
  </div>

  <div class="text-center mb-4">
    <%= form.submit "Atualizar item", class: "btn btn-primary me-2" %>
  </div>
<% end %>

<div class="text-center mb-4 d-flex justify-content-center">
  <%= button_to "Excluir item", sale_path(@sale), method: :delete, data: { confirm: "Você tem certeza que deseja excluir este item?" }, class: "btn btn-danger me-2" %>
</div>

app/views/sales/index.html.erb
<div class="container">
  <div class="text-center my-4">
    <%= button_tag 'Exportar', class: 'btn btn-primary', data: { toggle: 'modal', target: '#exportModal' } %>
  </div>

  <div class="table-responsive" style="max-height: 400px; overflow-y: auto;">
    <table class="table table-striped table-bordered">
      <thead class="thead-dark">
        <tr>
          <th>Nome do Comprador</th>
          <th>Descrição do Item</th>
          <th>Preço do Item</th>
          <th>Quantidade Comprada</th>
          <th>Endereço do Comerciante</th>
          <th>Nome do Comerciante</th>
          <th class="sticky-column">Ações</th> <!-- Ação com classe para fixar -->
        </tr>
      </thead>
      <tbody>
        <% @sales.each do |sale| %>
          <tr>
            <td><%= sale.purchaser_name %></td>
            <td><%= sale.item_description %></td>
            <td><%= number_to_currency(sale.item_price) %></td>
            <td><%= sale.purchase_count %></td>
            <td><%= sale.merchant_address %></td>
            <td><%= sale.merchant_name %></td>
            <td class="sticky-column">
              <%= link_to 'Editar', edit_sale_path(sale), class: "btn btn-warning btn-sm" %> <!-- Botão pequeno para melhor responsividade -->
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <p class="text-center font-weight-bold text-success">Total: <%= number_to_currency(@total_income) %></p>


  <%= button_to 'Excluir Tabela', destroy_all_sales_path, method: :delete, data: { confirm: 'Tem certeza que deseja excluir todas as vendas?' }, class: "btn btn-danger mx-auto d-block" %>

  <!-- Modal para Exportar -->
  <div class="modal fade" id="exportModal" tabindex="-1" role="dialog" aria-labelledby="exportModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exportModalLabel">Exportar Vendas</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <form action="<%= export_sales_path %>" method="get">
            <div class="form-group">
              <label for="format">Escolha o formato:</label>
              <select name="format" id="format" class="form-control">
                <option value="csv">CSV</option>
                <option value="xlsx">XLSX</option>
              </select>
            </div>
            <button type="submit" class="btn btn-primary">Exportar</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

<style>
  .table-responsive {
    position: relative;
    max-height: 400px; /* Define a altura máxima da tabela, ajuste conforme necessário */
    overflow-y: auto; /* Adiciona a barra de rolagem vertical quando o conteúdo ultrapassa a altura máxima */
  }

  /* Fixa o cabeçalho */
  th {
    position: sticky; 
    top: 0; 
    background-color: #343a40; 
    color: white; 
    z-index: 10; /* Para que o cabeçalho fique acima do conteúdo */
  }

  /* Fixa a coluna de ações */
  .sticky-column {
    position: sticky; 
    right: 0; 
    background-color: white; 
    z-index: 9; /* Para que a coluna de ações fique acima do conteúdo */
  }

  /* Para garantir que o fundo da coluna de ações fique visível */
  td.sticky-column {
    background-color: white; /* Cor do fundo para a coluna de ações */
  }
</style>

app/views/sales/new.html.erb
<div class="container-fluid"> <!-- Troquei para container-fluid para aumentar a largura -->
  <div class="row justify-content-center">
    <div class="col-lg-10 col-md-10 col-sm-12"> <!-- Aumentei a largura das colunas -->
      <div class="card">
        <div class="card-body">
          <!-- Carrossel de imagens -->
          <div id="imageCarousel" class="carousel slide mb-4" data-ride="carousel" data-interval="3500">
            <div class="carousel-inner">
              <div class="carousel-item active">
                <img src="/txt.png" class="d-block w-100 img-fluid" alt="Imagem de exemplo" style="max-height: 280px;">
              </div>
              <div class="carousel-item">
                <img src="/CSV.png" class="d-block w-100 img-fluid" alt="Imagem de exemplo" style="max-height: 280px;">
              </div>
              <div class="carousel-item">
                <img src="/gratis.png" class="d-block w-100 img-fluid" alt="Imagem de exemplo" style="max-height: 280px;">
              </div>
            </div>
            <a class="carousel-control-prev" href="#imageCarousel" role="button" data-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="sr-only">Anterior</span>
            </a>
            <a class="carousel-control-next" href="#imageCarousel" role="button" data-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="sr-only">Próximo</span>
            </a>
          </div>

          <%= form_with(url: sales_path, local: true, multipart: true) do |form| %>
            <div class="form-group">
              <%= form.label :file, "Arquivo .txt ou .tab" %>
              <%= form.file_field :file, class: 'form-control', id: 'fileUpload', accept: '.txt' %>
              <div id="file-name" class="mt-2"></div>
            </div>
            <div id="drop-area" class="border border-primary text-center p-4 my-3" 
                 ondrop="dropHandler(event)" 
                 ondragover="dragOverHandler(event)" 
                 onclick="clickHandler()">
              <p>Arraste e solte o arquivo aqui ou clique para selecionar</p>
            </div>

            <div class="text-center">
              <%= form.submit "Fazer Upload", class: 'btn btn-primary' %>
            </div>
          <% end % %>
        </div>
      </div>
    </div>
  </div>
</div>